-- Draftwell cloud storage schema
-- Run this in Supabase SQL Editor.

create table if not exists public.projects (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'Untitled project',
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chapters (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  chapter_number integer not null,
  title text not null,
  note text not null default '',
  body text not null default '',
  status text not null default 'Outline',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists projects_user_id_idx on public.projects(user_id);
create index if not exists chapters_project_id_idx on public.chapters(project_id);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  message text not null default '',
  kind text not null check (kind in ('first-minute', 'monthly')),
  created_at timestamptz not null default now()
);

create index if not exists feedback_user_id_idx on public.feedback(user_id);

alter table public.projects enable row level security;
alter table public.chapters enable row level security;
alter table public.feedback enable row level security;

drop policy if exists "Users can manage their projects" on public.projects;
create policy "Users can manage their projects"
  on public.projects for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can manage their chapters" on public.chapters;
create policy "Users can manage their chapters"
  on public.chapters for all
  using (
    exists (
      select 1 from public.projects
      where projects.id = chapters.project_id
        and projects.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.projects
      where projects.id = chapters.project_id
        and projects.user_id = auth.uid()
    )
  );

drop policy if exists "Users can submit feedback" on public.feedback;
create policy "Users can submit feedback"
  on public.feedback for insert
  with check (auth.uid() = user_id);

-- Create a Storage bucket named "covers" in Storage, then add:
-- insert into storage.buckets (id, name, public) values ('covers', 'covers', false);
-- Storage policies should restrict object paths to auth.uid().
